title: ARGAWANDA ARDIAN
description: Mahasiswa Sistem Informasi

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: SIF
   url: //sif.uin-suska.ac.id/
 - title: UIN
   url: //uin-suska.ac.id/

social:
   github: argawandaardian
   twitter: argawanda
   facebook: Argawanda Ardian
   email: argawandaardian@gmail.com

google_analytics: "UA-58263416-1"
